"""
End-to-end runtime evidence test.

Uses the trace file already generated by scripts/collect_traces.py.
Runs two assertions:
  1. Log4Shell payload  → OBSERVED   (run1.log)
  2. Benign payload     → NOT_OBSERVED (run2.log, if it exists)

Run:
    python scripts/collect_traces.py                        # Log4Shell payload
    python scripts/collect_traces.py --payload hello --output run2.log
    python analyzer/test_runtime.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from seed_loader import load_seed
from runtime_analyzer import analyze_traces, parse_trace_log, print_trace_summary

ROOT = Path(__file__).parent.parent
SEEDS_DIR   = ROOT / "data" / "seeds"
TRACES_DIR  = ROOT / "data" / "traces"


def test_log4shell_observed():
    print("=" * 60)
    print("Test: CVE-2021-44228 runtime trace — expected: OBSERVED")
    print("=" * 60)

    seed = load_seed(SEEDS_DIR / "CVE-2021-44228.yaml")
    vm = seed.primary_method

    trace_file = TRACES_DIR / "run1.log"
    if not trace_file.exists():
        print(f"  SKIP: {trace_file} not found — run scripts/collect_traces.py first")
        return None

    spans = parse_trace_log(trace_file)
    print_trace_summary(spans, vm)

    evidence = analyze_traces(trace_file, vm)

    print(f"\n  Status     : {evidence.status.value}")
    print(f"  Confidence : {evidence.confidence}")
    print(f"  Call count : {evidence.observed_call_count}")
    if evidence.trace_ids:
        print(f"  Trace IDs  : {evidence.trace_ids}")

    print()
    if evidence.status.value == "observed":
        print("  PASS: JndiLookup.lookup OBSERVED in runtime trace")
        return True
    else:
        print(f"  FAIL: Expected observed, got {evidence.status.value}")
        return False


def test_benign_not_observed():
    print("=" * 60)
    print("Test: benign payload runtime trace — expected: NOT_OBSERVED")
    print("=" * 60)

    seed = load_seed(SEEDS_DIR / "CVE-2021-44228.yaml")
    vm = seed.primary_method

    trace_file = TRACES_DIR / "run2.log"
    if not trace_file.exists():
        print(f"  SKIP: {trace_file} not found")
        print("  Run: python scripts/collect_traces.py --payload hello --output run2.log")
        return None

    spans = parse_trace_log(trace_file)
    print_trace_summary(spans, vm)

    evidence = analyze_traces(trace_file, vm)

    print(f"\n  Status     : {evidence.status.value}")
    print()
    if evidence.status.value == "not_observed":
        print("  PASS: JndiLookup.lookup NOT OBSERVED with benign payload")
        return True
    else:
        print(f"  UNEXPECTED: Got {evidence.status.value}")
        return False


if __name__ == "__main__":
    r1 = test_log4shell_observed()
    print()
    r2 = test_benign_not_observed()

    if r1 is False:
        sys.exit(1)
